codecov:
  require_ci_to_pass: true

# Comentário em PR só quando fizer sentido (evita ruído)
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: "coverage_drop OR uncovered_patch"
  require_base: true
  require_head: true

coverage:
  status:
    # Status 1: piso mínimo absoluto
    project:
      minimum:
        target: 60%
        threshold: 0
        flags:
          - backend
        informational: false

      # Status 2: guardrail contra queda em relação ao base
      guardrail:
        target: auto
        threshold: 1
        flags:
          - backend
        informational: false

    # Status de patch (novo código): começa um pouco mais exigente
    patch:
      default:
        target: 70%
        threshold: 0
        flags:
          - backend
        informational: false

# Intencionalmente SEM ignore neste ticket:
# só vamos ignorar pastas depois de mapear pacotes reais e justificar (ex.: código gerado, boilerplate, etc.)